#!/bin/bash

# palettegen - 2019-03-10 by knuxify
# I randomly decided to make a program that generates 
# infinite gradients, that randomly switch from color 
# to color. While I did not achieve that, what came 
# out of it was a small palette generator that uses 
# true color.

echo ""
MAX=256
r=$(( ( RANDOM % $MAX )  + 1 ))
    g=$(( ( RANDOM % $MAX )  + 1 ))
    b=$(( ( RANDOM % $MAX )  + 1 ))
printcol() {
	printf "\x1b[48;2;$r;$g;${b}m$1\x1b[0m"
}
	printcol
	oldr="$r"
	oldg="$g"
	oldb="$b"
	r="100"
    g="100"
    b="100"
		until [ "$r" -eq "$oldr" ]; do
			if [ "$r" -gt "$oldr" ]; then let r--; else let r++; fi
			printcol "[ $r, $g, $b ]"
		done
		until [ "$g" -eq "$oldg" ]; do
			if [ "$g" -gt "$oldg" ]; then let g--; else let g++; fi
			printcol "[ $r, $g, $b ]"
		done
		until [ "$b" -eq "$oldb" ]; do
			if [ "$b" -gt "$oldb" ]; then let b--; else let b++; fi
			printcol "[ $r, $g, $b ]"
		done
echo ""
