#!/bin/bash

# usageman by knuxify - 2019-03-10
# just wanted something to make my .bashrc cooler ;)
# only works with 4-digit ram configurations. I won't fix this, probably.

echo "RAM: $(free -m | grep Mem: | cut -c 28-31)MB/$(free -m | grep Mem: | cut -c 16-19)MB used"
